# Generated by Django 3.2.5 on 2021-08-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210803_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default=True, max_length=255),
        ),
    ]
